apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: zlatanovics/auth
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
